### ISSUE TITLE
Llover

### ISSUE THREAD

**Issue by anotherpit** [jirimracek/conjugate-esp#20]
What the lib gives:

```typescript
new Conjugator('2010').conjugateSync('llover', 'castellano')
```

```json5
[
  {
    info: { model: 'mover', region: 'castellano' },
    conjugation: {
      Indicativo: {
        // ...
        Presente: [
          'lluevo',
          'llueves',
          'llueve',
          'llovemos',
          'llovéis',
          'llueven'
        ],
        // ...
      },
      // ...
    },
    // ...
  }
]      
...
```

What WordReference [gives](https://www.wordreference.com/conj/esverbs.aspx?v=llover):
```yaml
presente:
  yo: –
  tú: –
  usted: llueve
  nosotros: –
  vosotros: –
  ustedes: –
  vos: –
```

Bug or somehow intended result?
